---
- name: install maven
  hosts: db
  become: yes

  tasks:

  - name: Ensure maven package is present
    apt:
      name: maven
      state: present

- name: git 
  hosts: db

  tasks:

  - git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
      dest: /tmp/maven

- name: maven pkg
  hosts: db
  become: yes

  tasks:

  - name: Execute maven
    shell: mvn package
    
- name: copy
  hosts: db

  tasks:

  - name: Copy file from remote host to local machine
    fetch: 
      src: /tmp/maven/target/hello-1.0.war
      dest: /tmp/boxfuse.war

- name: Install tomcat  
  hosts: web
  become: yes

  tasks:

  - name: Ensure tomcat package is present
    apt:
      name: tomcat9
      state: present

- name: install jdk
  hosts: web
  become: yes

  tasks:

  - name: Ensure jdk package is present
    apt:
      name: default-jdk
      state: present
  
- name: Copy file from local host to remote machine
  hosts: web
  become: yes
  
  tasks:

  - name: Ensure boxfuse file is present
    copy:
      src: boxfuse.war
      dest: /var/lib/tomcat9/webapps

- name: Ensure tomcat service is started
  hosts: web
  become: yes

  tasks:     

  - name: Ensure tomcat service is started
    service:
      name: tomcat
      state: started
